### ISSUE TITLE
Previous issue with uploads

### ISSUE THREAD

**Issue by WarlordZudane** [Cadrach/lol_ise#1]
### Browser Firefox 50.1

Couldn't get the upload to work right, ended up being an old Flash installation that wasn't removed when updated.  Had to totally remove Flash and reinstall to fix the problem, uploads by drag and drop work fine in Firefox now, although all champions get all item sets.  Or most of them it seems to be randomly selected from the list if there are too many.   The screenshot below shows what it looks like in the background - just to be clear I have only general item sets that I have named for what champions I use them on, and no champion-specific item sets.

And on Firefox it's not possible to download the files, it ends up here: http://i.imgur.com/i5EoWun.png and nothing happens.  I figure it works in Chrome so I can still use it there at least, might want to add a disclaimer it works on Chrome.

Still failing to upload a zip on here though.  https://we.tl/Qa8z97d66S for the download of my config.

**Comment by Cadrach** [comment]
Perfect thanks! I will get a look at this tomorrow. 

If I understand it work correctly on **Chrome Windows 10** now, except that you cannot drag & drop a folder to the window?

**Comment by WarlordZudane** [comment]
Drag and drop does work now, that was a Flash related problem.  Uninstall and reinstall worked on that.

**Comment by Cadrach** [comment]
Ok, I will implement tomorrow a feature to allow you to upload a zip file into the tool. Currently however, from what you gave me, it is normal to have all sets loaded for all characters, as you have a folder per champion, with every time the same 10 sets.

If you want to clear that up, you can do the following:

- Delete your **Config/Champions** folder
- Unzip the following [Config_Warlord_Fixed.zip](https://github.com/Cadrach/lol_ise/files/662535/Config_Warlord_Fixed.zip) into the "Config" folder. 
- You should now have only a **Global** folder in the **Config** folder (and next to it your other config files)

This is how Global sets should be configured, you folder tree should in the end be like this:
____
=== Config
======= * game.cfg
======= * input.ini
======= * ItemSets.json
======= * LCUAccountPreferences.yaml
======= * LCULocalPreferences.yaml
======= * LeagueClientAccountSettings.yaml
======= * LeagueClientSettings.yaml
======= * PersistedSettings.json
======== Global
============ Recommended
============== * RIOT_ItemSet_1.json
============== * RIOT_ItemSet_10.json
============== * RIOT_ItemSet_11.json
============== * RIOT_ItemSet_2.json
============== * RIOT_ItemSet_3.json
============== * RIOT_ItemSet_4.json
============== * RIOT_ItemSet_5.json
============== * RIOT_ItemSet_6.json
============== * RIOT_ItemSet_7.json
============== * RIOT_ItemSet_8.json
============== * RIOT_ItemSet_9.json

**Comment by Cadrach** [comment]
Pushed a new version where you can upload a .zip, so you can simply use my zip file if you want and upload it. You should still delete your Champions folder before deploying again though.

**Comment by WarlordZudane** [comment]
Took me a day to get back to it but I just checked and it all seems to be working.  Great work!

I hadn't modified the files before, so I can't help but wonder why it's like that.  Could it be that the old client used the itemsets.json file as a whole and it was translated to the champions folders as a copy to each one?  I honestly can't really understand how I can delete the entire champions folder, replace it with a single Global folder and still have all of the same item sets and recommended item sets.

**Comment by Cadrach** [comment]
Yeah, I am starting to think there are issues on Riot's side when they move from Legacy to New Client and back and forth.

Meanwhile I have tested on Firefox (latest: 50.1.0) without any problem, so I am closing this issue. Please re open it if you still have problems after updating Firefox & clearing your cache!
