### ISSUE TITLE
Import from Mobafire

### ISSUE THREAD

**Issue by Toilal** [Cadrach/lol_ise#11]
First of all thanks for this awesome tool :)

It's only an idea, but it would be great to be able to import a build from [mobafire](http://www.mobafire.com/league-of-legends/browse). 

I'm also an AngularJS developer, so if you are open to pull requests, I could try to work on this on my spare time. Tell if you are interested about this idea ...

**Comment by Cadrach** [comment]
Hey, if you want to go ahead! I did not know Mobafire had an export format for their build.

Keep in mind the following when adding features:

- Must be clear for the end user, and not clutter the interface (in this case, probably a menu in the cogs wheel of the current set that would open a dedicated modal)
- No server side code, I want to try and keep the tool lightweight and do not want yet to store anything server side
- Commented code :)

Do not hesitate to reach out if you want more info!

**Comment by Toilal** [comment]
Mobafire doesn't have any export format. 

I was thinking of performing a javascript HTTP Request to parse the HTML page from Mobafire, but I don't think it will require some [CORS](http://enable-cors.org/) configuration on the server.

**Comment by Cadrach** [comment]
If you need CORS, I can add script on the server in PHP to do that. It would accept only URL to mobafire (so probably extract the ID of the build from the passed URL, rebuild a secure URL and fetch that for the tool). What do you think? 

You would pass something like this: 
`http://www.mobafire.com/league-of-legends/build/amumu-wrapping-up-the-jungle-37186`
And the script would fetch this:
`http://www.mobafire.com/league-of-legends/build/37186`

**Comment by Cadrach** [comment]
I have pushed a php script that returns a build from lolking as a JSON set. I will next add the interface in the tool to import the set from the guide (and make room for mobafire too)

How are you proceeding with the feature? I can do it for mobafire too if you want.

**Comment by Toilal** [comment]
Yes go ahead if you are ready ! Peu de temps, et j'ai passé un peu de temps
sur le nouveau squelette du pull request, il me reste un problème a régler
encore.

**Comment by Cadrach** [comment]
Du coup je le fais pour mobafire aussi? Ca renverra un json propre direct normalement. Ou plusieurs sets même car je crois que sur mobafire on peut en avoir plusieurs par page.

**Comment by Toilal** [comment]
Oui oui fait le ☺️ merci ! Ça sera plus simple de le faire en PHP plutôt
qu'en full javascript.

**Comment by Cadrach** [comment]
Deployed in 0.8

**Comment by EagleExe** [comment]
2020 version here https://github.com/EagleExe/LoL-ItemsJSON
