### ISSUE TITLE
NodeJS / Gulp build

### ISSUE THREAD

**Issue by Toilal** [Cadrach/lol_ise#13]
Would you agree to use another skeleton for the project, to have a nodeJS/Gulp based build in order to produce the JSON files during the build, and minify the whole project to enhance first load of the app ?

I'm used of [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular), that has been refactored into [FountainJS](http://fountainjs.io/), it's really handy ...

**Comment by Cadrach** [comment]
I will look at it tonight or tomorrow and let you know!

**Comment by Cadrach** [comment]
In fact you can go ahead right away, I will integrate your first PR later today.
