### ISSUE TITLE
item sets don't match in game

### ISSUE THREAD

**Issue by anoda9** [Cadrach/lol_ise#15]
### Browser (Chrome, Safari, Internet Explorer) and Version
google chrome Version 55.0.2883.95 (64-bit)

### Provide a Screenshot when possible
I create this item set:
![screen shot 2017-01-14 at 7 39 30 am](https://cloud.githubusercontent.com/assets/3486897/21956053/c5ba739a-da2c-11e6-96c4-1b009d859613.png)

and download this json file:
{"title":"sejuani custom","map":"any","mode":"any","type":"custom","priority":false,"sortrank":null,"champion":"Sejuani","blocks":[{"type":"startingjungle","recMath":false,"items":[{"id":1039,"count":1},{"id":2031,"count":1},{"id":3340,"count":1},{"id":2055,"count":1}]},{"type":"early","recMath":false,"items":[{"id":"1413","count":1},{"id":1401,"count":1},{"id":1001,"count":1},{"id":"3136","count":1}]},{"type":"essential","recMath":false,"items":[{"id":3742,"count":1},{"id":"3065","count":1},{"id":"3151","count":1},{"id":"3009","count":1}]},{"type":"finish","recMath":false,"items":[{"id":3075,"count":1},{"id":3143,"count":1},{"id":3083,"count":1},{"id":"3026","count":1},{"id":"3512","count":1},{"id":3102,"count":1},{"id":"3190","count":1},{"id":"3158","count":1},{"id":"3111","count":1}]},{"type":"consumables","recMath":false,"items":[{"id":2138,"count":1},{"id":"3363","count":1},{"id":"2139","count":1},{"id":"3364","count":1}]}]}

but these are the items that show up in game:
![screen shot 2017-01-14 at 7 39 41 am](https://cloud.githubusercontent.com/assets/3486897/21956055/ca43bd04-da2c-11e6-89bf-493d01af44b7.png)

(the order of some of them might be slightly different, but the basic idea is that not all the items show up, some blocks are completely missing, etc.)

**Comment by Aerhyce** [comment]
I am having the exact same issue, on Firefox.

This did not happen before.

**Comment by Cadrach** [comment]
I will look at it tomorrow morning thanks for the report!

**Comment by Cadrach** [comment]
Could you tell me how you first created this set? Is it from the default sets of Riot?

**Comment by Aerhyce** [comment]
The default set automatically appears, I don't know how to create an empty new set.

I tried to make the exact same item set twice, the first using the Riot set and adding/removing items/blocks, and the second starting by deleting every block, then make everything from scratch.

Set 1: Many missing items.
Set 2: No missing items.

On the website, they are visually the same.

**Comment by Cadrach** [comment]
This was bothering me so it should now be fixed in release 0.9

**Comment by Cadrach** [comment]
FYI, the default sets provided by Riot are at fault: the id of the items are of type "integer" when the game accepts only "strings" as ids...
