### ISSUE TITLE
Items not appearing ingame

### ISSUE THREAD

**Issue by hawezo** [Cadrach/lol_ise#16]
I noticed some items didn't appear ingame while I was sure I put them in my sets.
After looking at the files created by the item set editor, I find out what was the issue.
The correct format for JSON is  `{"id":"3157","count":1}` but this item had this markup : `{"id":3157,"count":1}`.
I noticed this for the Zhonya and te Hextech Gunblade.

**Comment by Cadrach** [comment]
This has been solved with version 0.10
I have also put a backward fix in place, so you should just redownload your sets & redeploy it should fix it.

For more information look #15
