### ISSUE TITLE
Unable to Delete without browser dialog being created.

### ISSUE THREAD

**Issue by LordHaphestus** [Cadrach/lol_ise#17]
### Browser Chrome
When you block a site from creating additional dialogue pop ups and try to delete an item block it wont allow you because you haven't said that its OK. instead of an alert you need to use something else so people can block the additional dialogue without issue.

**Comment by Cadrach** [comment]
I will look into it for next version. In the meantime you can renable from somewhere in Chrome settings:
https://support.google.com/chrome/answer/3220216?hl=en
