### ISSUE TITLE
Cannot change champion mapped to an item set

### ISSUE THREAD

**Issue by NeonJalapeno** [Cadrach/lol_ise#20]
### Steps to reproduce
* load item set
* I cannot find a way to change the champion (or champions) that an item set is mapped to.
This applies for:
* item sets mapped to one champion
* item sets mapped to multiple champions
* item sets not mapped to a champion

**Comment by Cadrach** [comment]
This feature is currently not implemented

There is a very simple workaround however: duplicate the set to another champion, and then delete the original one.

I most likely will not implement this, unless there is a high demand for it, since duplicating already offers the feature.
