### ISSUE TITLE
Cannot create a new global set

### ISSUE THREAD

**Issue by rstarkov** [Cadrach/lol_ise#21]
Happens in Firefox and Chrome.

When I try to add a new global set, an error gets logged to the console, saying "cannot read property blocks of undefined". I also tried this yesterday and the error was different, saying something about angular.copy not being found I think.

**Comment by Cadrach** [comment]
Sorry for taking so long, did not have time to work on the project lately. Issue was linked to the loading of the "recommended" set when adding a new set.
