### ISSUE TITLE
Item Set Creation Fail

### ISSUE THREAD

**Issue by dvychen** [Cadrach/lol_ise#22]
I have invested a fair bit of time into creating an item set. However, when I downloaded it off the website, then re-uploaded (to check if it was successful) the "Config" folder I just downloaded, it was lacking an entire item set. Please fix this, as I did not wish to have to downgrade to the legacy client to update my item sets.

**Comment by Cadrach** [comment]
Before we start, let me just remind you that I am developing this for free, on my free time. Keep it in mind when asking for me to fix something for you.

This being said, I need more information about your bug:

- Do you have a the zip you downloaded from the tool?
- Which exact item set is missing from it (champion & set name)

Thanks,

**Comment by Cadrach** [comment]
Please reopen once you are able to provide more information, thanks!
