### ISSUE TITLE
Item tooltips not adjusting to window border

### ISSUE THREAD

**Issue by Myrmidonut** [Cadrach/lol_ise#23]
### Browser (Chrome, Safari, Internet Explorer) and Version
Chrome Version 57.0.2987.98 beta (64-bit)

### Provide a Screenshot when possible
![image](https://cloud.githubusercontent.com/assets/26467570/24012555/b6ba0446-0a7e-11e7-83a9-0f36f90920fa.png)

### Steps to reproduce
Tooltips for items on the right side in the itemset blocks are not adjusting to the browser window borders. They are always aligned with their middlepoint and if you made a few blocks half of the tooltip is outside the browser, maybe use the same behaviour as you use for the ones in the overview?

**Comment by Cadrach** [comment]
Thanks for your feedback, I will take a look at this next week!
