### ISSUE TITLE
Unable to download item sets on Firefox browser.

### ISSUE THREAD

**Issue by GnothiSeauton34** [Cadrach/lol_ise#24]
### Browser (Chrome, Safari, Internet Explorer) and Version:

Firefox Nightly(happens on Stable version too.). There's no problems downloading item sets on Chrome browser, Stable and Canary versions work fine.

### Provide a Screenshot when possible

https://puu.sh/uUl7s/897b7077e9.gif - Gif that shows you what happens when you click download in Firefox browser.

**Comment by Cadrach** [comment]
Hi,

Thanks for the gif, I will look at this this week!
