### ISSUE TITLE
Site seems to enter "codeVersion" after one use or after changing langage settings

### ISSUE THREAD

**Issue by miniele** [Cadrach/lol_ise#25]
### Browser (Chrome, Safari, Internet Explorer) and Version
Tried Firefox 52.0.1, Chrome 57.0.2987.110, Internet Explorer 11.953.14393.0 and Edge 38.14393.0.0
### Provide a Screenshot when possible
![lol item set](https://cloud.githubusercontent.com/assets/26741122/24405446/28737974-13c5-11e7-81de-0cac46ee17e4.JPG)

### Steps to reproduce
Like I described in the title, the site seems to enter the screenshotted mode after one use or changing the language. after this first happened in firefox i tried using edge and internet explorer which didn't work (surprise - who uses them anyway?), so installed chrome, could download once, closed the window and played lol. When i tried to create another set it once again entered the i-can-do-nothing-mode and never went back, even after deleting cookies and cache, same goes for firefox.
nothing is clickable exept "bugs", this is how i came here.

**Comment by Cadrach** [comment]
I just tried on the live version with clearing cache and it worked correctly. Could you try again?

If it persist, could you run your site with the developer console open, and copy paste everything it displays here?

**Comment by Cadrach** [comment]
This might have been due to an issue with automatic update against the Riot API. Please re-open if you can reproduce the bug, or can provide debug console information, thanks!
