### ISSUE TITLE
Unable to upload on macOS

### ISSUE THREAD

**Issue by bcc32** [Cadrach/lol_ise#27]
### Browser (Chrome, Safari, Internet Explorer) and Version
Tested on Chrome 57 and Firefox 51
### Provide a Screenshot when possible
![Imgur](http://i.imgur.com/pN9aP21.png)
### Steps to reproduce
1. Drag `/Applications/League of Legends.app/Contents/LoL/Config` to window.
2. Check JS console output.
3. `Wrong format, missing: type,map,mode,blocks,champion`

**Comment by Cadrach** [comment]
Could you provide me with a .zip of your Config folder? Thanks!

**Comment by bcc32** [comment]
[Config.zip](https://github.com/Cadrach/lol_ise/files/887784/Config.zip)

**Comment by Cadrach** [comment]
This is really strange, your sets are all stored in one single **ItemSets.json** file, which is not the usual way. I have a local fix done, but I want to look at the Riot API first to see if this is expected.

**Comment by bcc32** [comment]
Not sure why this is.  Some additional information that might be helpful (?): I didn't have any .json files in my config (and no available item sets) until I re-ran the legacy client.  After doing so, the ItemSets.json file appeared.

**Comment by Cadrach** [comment]
When you run LoL on MacOS, do you have any custom sets, when running a custom game for example?

**Comment by bcc32** [comment]
It only works when I launch the game from the legacy client.

**Comment by Cadrach** [comment]
Could you try using your Config file from the PC on your Mac and see if it works?

**Comment by bcc32** [comment]
So, after having launched the game from the legacy client, the item set _for that champion only_ appears in the newly-created Champions/ folder.  I can then use the item set _for that champion only_ when launching from the new client.

Dumping the Config folder from my PC into my Mac allows item sets to work fine from the new client, although my screen rez and other settings obviously break.

**Comment by Cadrach** [comment]
You can drop only the Champions folder to keep tour settings. Also, I think this is expected, you must run a custom game on legacy to create the folder.

With that you should be all set, could you confirm so that I can close this issue?

**Comment by bcc32** [comment]
Fair enough.  It is strange that I need to run a custom game on legacy with each individual champion for whom I have an item set in order to get it to appear, and I certainly wouldn't call this "expected" behavior, but if you think handling this case is outside the scope of your project, please feel free to close the issue.

**Comment by Cadrach** [comment]
From what I got from a few friends which do not want to use my tool to spite me, they have to run a custom game on the legacy client every time they make a change to custom sets. I did not know they had to run it for the specific champion they were changing it for, but it might be the case.

Closing this then, feel free to re-open if you think there is something to fix!
