### ISSUE TITLE
zip file with wrong folder structure

### ISSUE THREAD

**Issue by Myrmidonut** [Cadrach/lol_ise#28]
### Browser (Chrome, Safari, Internet Explorer) and Version
Chrome Version 57.0.2987.133 (64-bit)

### Steps to reproduce
I uploaded a zip file that i created earlier and when i download the zip file again it has the following structure:

Lol_Item_Set.zip\Config\Global\Recommended\Config\Global\Recommended\Global0.json

I think it remembers the file structure in the old zip file and just adds another \Config\Global\Recommended\ . Only in the last Recommended folder are .json files.
I uploaded the wrong zip file again and then downloaded the sets and it adds another batch of those three folders. It shows the sets in the website just fine.

**Comment by Cadrach** [comment]
Could you give me the bad zip file generated? Thanks!

**Comment by Myrmidonut** [comment]
Thats the one i got after uploading the old one:
[Lol_Item_Set.zip](https://github.com/Cadrach/lol_ise/files/900280/Lol_Item_Set.zip)

And thats the one I got after uploading the above one:
[Lol_Item_Set (3).zip](https://github.com/Cadrach/lol_ise/files/900284/Lol_Item_Set.3.zip)

I uploaded using the zip file method by the way.

**Comment by Myrmidonut** [comment]
I still have the same issue... I resettet everything by uploading just my .json files and the downloaded .zip file is now back to normal. But when i upload this .zip file and download it again i get the same duplicate folder structure as before.

**Comment by Wilsonfabozi** [comment]
Also, when you duplicate for another champion, the file gets the name from the orinigal champion, the one you copied it for

**Comment by Cadrach** [comment]
When you read the version number at the top, does it read 0.12?

**Comment by Myrmidonut** [comment]
Ok its working now! I believe I was still on 0.11, maybe it didn't update yet and I was too fast. Good job! :-D

**Comment by Cadrach** [comment]
Ok, that is reassuring because I did not know how it could still happen after this fix ^_^

**Comment by Wilsonfabozi** [comment]
Now its working, and it says 0.12
