### ISSUE TITLE
Global Sets Not Working

### ISSUE THREAD

**Issue by tylerdefoor** [Cadrach/lol_ise#30]
### Browser (Chrome, Safari, Internet Explorer) and Version
Chrome
### Provide a Screenshot when possible
![image](https://cloud.githubusercontent.com/assets/13808546/25110202/e9b6da96-2396-11e7-8a6b-6af41d0e2d13.png)
![image](https://cloud.githubusercontent.com/assets/13808546/25110212/f65dfc98-2396-11e7-84ed-a5d9954d426d.png)
### Steps to reproduce
1. Create global item set in Chrome
2. Download and copy over to League of Legends folder
3. Launch in new client
4. Items not in game

Hello!
I love the work you're putting into this! I don't seem to be able to get global item sets to work at all. The attached screenshot shows that my item sets are at an earlier version from what I have downloaded. I have not tested this on other browsers. I will attach the config file and the item set I downloaded. 

[Config.zip](https://github.com/Cadrach/lol_ise/files/927016/Config.zip)
[Lol_Item_Set (2).zip](https://github.com/Cadrach/lol_ise/files/927020/Lol_Item_Set.2.zip)

I have gotten around this by adding each champion I could want a specific item set for manually. 

For instance, Warwick now has 2 AD Jungle pages.
![image](https://cloud.githubusercontent.com/assets/13808546/25110356/3832b216-2398-11e7-8e7b-357fb70b8164.png)

One of which is correct
![image](https://cloud.githubusercontent.com/assets/13808546/25110365/45503f0e-2398-11e7-980f-ee8d61133239.png)

The other is not
![image](https://cloud.githubusercontent.com/assets/13808546/25110371/50778018-2398-11e7-919f-6948eb13eb0d.png)

You can see how the bottom image is missing all the bloodrazor enchants and the control ward.

Let me know if you need any more info!

**Comment by Cadrach** [comment]
Hi! Could you try the following: launch a custom game with Warwick, then reload your item set into the tool.

The thing is, if you edit your sets in the legacy client, you need to launch at least one game with the champion to have the client create them in the folder.

Let me know if this solves it.

**Comment by Cadrach** [comment]
Closing as I did not get any feedback for about 2 weeks, please reopen if you have an update!
