### ISSUE TITLE
Downloading settings is impossible

### ISSUE THREAD

**Issue by LunarBird** [Cadrach/lol_ise#32]
### Provide a Screenshot when possible
https://zapodaj.net/images/2632cd648d568.jpg
### Steps to reproduce

When working with Global Sets on Chrome and Vivaldi after setting them up it is impossible to download settings. The download just won`t start and no link to the file is shown.

**Comment by Cadrach** [comment]
Your screenshot shows Vivaldi, could you confirm that you have issues on Chrome? I just tested without a problem on my machine.

If the issue is only on Vivaldi let me know, I will deploy it and try to fix. If you want to check on your side, it my be due to Flash not being allowed on your side, as it is being used as a last resort solution on unsupported browsers.

**Comment by LunarBird** [comment]
I chacked on both Vivaldi and Chrome (in both cases in private window with all addons disabled). The problem remained the same. JavaScript was enabled.

My version of Vivaldi: 	1.9.818.25 (64-bit)
My version of Chrome:      57.0.2987.133 (64-bit)

**Comment by Cadrach** [comment]
Gould you open the debug console (F12 usually) in chrome, refresh the page and copy paste the error log here, if any?

**Comment by LunarBird** [comment]
Well, in Vivaldi in Console it displays something like this:
`Object {name: "Vivaldi", vivaldi: true, version: "1.9", blink: true, windows: true…}a: trueblink: truecheck: function check(minVersions, strictMode, ua)compareVersions: function compareVersions(versions)isUnsupportedBrowser: function isUnsupportedBrowser(minVersions, strictMode, ua)name: "Vivaldi"test: function (browserList)version: "1.9"vivaldi: truewindows: true_detect: function detect(ua)__proto__: Object`

It seems like it works in Chrome now. It doesn`t display the window with "Save" button though, it just downloads the file right away.

**Comment by Cadrach** [comment]
Ok, I will look at Vivaldi when I have the time, as long as their is no issue in Chrome it is less pressing!

**Comment by LunarBird** [comment]
I'm suggesting to make Vivaldi be recognized as Chrome. I just used User Agent Switcher to make my Vivaldi pretend to be Chrome. Works fine.

**Comment by Cadrach** [comment]
Indeed, should be straightforward, I'll let you know once it is fixed.
