### ISSUE TITLE
Item missing

### ISSUE THREAD

**Issue by Cleaveland** [Cadrach/lol_ise#34]
There is no "Total Biscuit of Rejuvenation"
http://prntscr.com/f1oubl
http://prntscr.com/f1ouf2

**Comment by LunarBird** [comment]
Isn't it just a Health Potion with Secret Stash mastery enabled?

**Comment by Cadrach** [comment]
Yes, I think so. I will look at the list of items still, in case it is there somewhere.

**Comment by Cleaveland** [comment]
Okay, just was setting up sets and noticed it, Just have been seeing tons of ppl using it and noticed it wasn't there :D

**Comment by Cadrach** [comment]
Ok, so the biscuit is indeed in the list of items, but it is tagged in the Riot API as "purchasable: false", and has no price. There are a lot of other items (usually champion, mode  or map specifics items) in this case so I have to keep this rule in.

From memory, I tend to say that in the legacy client it was not present either in the item set editor.
