### ISSUE TITLE
Download Button Doesn't Do Anything

### ISSUE THREAD

**Issue by Kloister** [Cadrach/lol_ise#35]
Chrome, have uBlockOrigin and tried disabling it - same issue.
Chrome version 57.0.2987.133 (Official Build) (64-bit)

Made an item set for zed, clicked download, nothing happens. No popup, no download, literally nothing. Tried to click gear in top right corner and download .JSON file and still nothing

Works fine using Edge

**Comment by Cadrach** [comment]
I have uBlockOrigin, PrivacyBadget and Adblock and it works fine on my side. There is a new Chrome version (58.0.3029.96) but I doubt it will be this.

Some things to try:

- Run the tool in incognito window (to simulate a cache clearing and start from fresh)
- In your classic window, open the console (F12) and copy paste the error messages when trying to download (if any)

**Comment by LunarBird** [comment]
>Chrome, have uBlockOrigin and tried disabling it - same issue.

Are you sure the file isn't being downloaded? I also have uBlock in Chrome and when it is disabled Download button doesn't display any window, but it downloads settings in ZIP archive.

Same thing in Vivaldi with User Agent Switcher set to Chrome.

**Comment by Cadrach** [comment]
Closing since no feedbacks
