### ISSUE TITLE
Champion List Not Alphabetized

### ISSUE THREAD

**Issue by chaoticnote** [Cadrach/lol_ise#37]
### Browser (Chrome, Safari, Internet Explorer) and Version
Chrome Version 58.0.3029.96 (64-bit)
### Provide a Screenshot when possible
![image](https://cloud.githubusercontent.com/assets/28378016/25689845/5c59f80c-3040-11e7-8edc-4238b2795466.png)

### Steps to reproduce
1) Pick a champion with item builds set up outside of LoL Item Set Editor.
2) Create new builds with LoL Item Set Editor.
3) Delete old builds not set up in LoL Item Set Editor.
4) Champion gets sent down all the way to the bottom of list.

I noticed this immediately as soon as I made new item builds on LoL ISE for Ashe and deleted her old ones. I thought it was bugged and the site deleted her, wasting my time and effort making her new build until I scrolled all the way to the bottom to find her there. Same thing happened with others below Ashe.

**Comment by Cadrach** [comment]
Yeah it is a pain, I have wanted to do it for some time but it is not as simple as it sounds because of the structure I have for sets.

Will add it for next version I think, as it is it looks really bad ^^

**Comment by chaoticnote** [comment]
Ah good to know it's been in thought. ^_^
