### ISSUE TITLE
Scrolling through the item list is unpleasantly slow

### ISSUE THREAD

**Issue by rstarkov** [Cadrach/lol_ise#4]
When the list of items is scrollable, it requires approximately 5 turns of my scrollwheel to go approximately 2.5 rows of items. It doesn't feel right at all. I can usually scroll through that much vertical space in an instant, with one quick turn of the scroll wheel.

It sure looks pretty the first time I scroll through it, but quickly becomes cumbersome when I'm just trying to find an item.

Nice work by the way!

**Comment by Cadrach** [comment]
Thanks, I will get a look at this. Could you provide me with your OS & Browser? Also, your screen resolution might help me reproduce.

**Comment by Cadrach** [comment]
This should have been solved in the latest release.
