### ISSUE TITLE
There is no download button

### ISSUE THREAD

**Issue by a12345678910987654321** [Cadrach/lol_ise#48]
![nayttokuva 1](https://cloud.githubusercontent.com/assets/29164670/26755112/72658730-488f-11e7-99e6-78e8e021e550.png)

**Comment by Cadrach** [comment]
What is your IE version?

**Comment by a12345678910987654321** [comment]
Do you mean Internet Explorer?

**Comment by Cadrach** [comment]
Yes :)

**Comment by Cadrach** [comment]
Closing since no feedback for about month, please reopen if you can provide some.
