### ISSUE TITLE
Visual Bug or something is wrong

### ISSUE THREAD

**Issue by WTFisWrong** [Cadrach/lol_ise#49]
### Browser (Chrome, Safari, Internet Explorer) and Version
Microsoft Edge 38.14393.1066.0
Microsoft EdgeHTML 14.14393
### Provide a Screenshot when possible
![untitled](https://user-images.githubusercontent.com/29314070/26993786-8b390942-4d19-11e7-99e1-1e9b1682a676.jpg)
### Steps to reproduce
No Facking Idea

**Comment by WTFisWrong** [comment]
I didn't have any problems before today.

**Comment by Cadrach** [comment]
Do you have an adblocker? If so can you try deactivating it?

**Comment by WTFisWrong** [comment]
I just checked it and it is back to normal.  I turned off and on adblock to test however same result, everything returned to normal.  Definitely not adblock.  
Visual bug's fault could be on my part, don't know for sure.

**Comment by Cadrach** [comment]
From the look of your bug, it seemed like you could not load the image from the Riot website, so maybe it was down at this time, or you had trouble reaching them (your ISP maybe?)

Closing this then, open again if it happens again :)
