### ISSUE TITLE
Item Sets I thought I deleted show up in downloaded file

### ISSUE THREAD

**Issue by chaoticnote** [Cadrach/lol_ise#51]
### Browser (Chrome, Safari, Internet Explorer) and Version
Chrome ver. 58.0.3029.110 (64-bit)**
### Provide a Screenshot when possible
![image](https://user-images.githubusercontent.com/28378016/27584005-3fd33196-5aeb-11e7-81b2-ede0aacf4880.png)
https://i.gyazo.com/45d43ad29a59920c3c893e4adb095c8e.png
### Steps to reproduce
I thought I had deleted the two item builds I highlighted up above, but for whatever reason they stuck around. It happens when downloading all the builds at once of course.

**Comment by Cadrach** [comment]
Hi,

This is expected, basically to remove a set you must delete the file, and the tool has no way to do that directly.

If you want what you downloaded to be exactly what you used, before merging the download with your Config folder, you should delete the Champions and Global folder inside the Config folder.

Please reopen if this does not solve your issue!

**Comment by chaoticnote** [comment]
Not really sure how deleting the Global folder will do anything since it has nothing inside it. Also these two files showed up in the downloaded folder itself. Not in RiotGames' folder.

**Comment by chaoticnote** [comment]
I figured out a workaround. Basically I downloaded the folder, unzipped, went into Fiddlestick's folder, deleted the files that kept appearing despite being deleted on the website, then drag+dropped the folder onto the website.
