### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by ChaPunch** [Cadrach/lol_ise#54]
Since the appearance of the 7.17 patch, the icons of most items have been tangled with each other, and also some champion names dont corespond the icon they show.

![untitled 1](https://user-images.githubusercontent.com/31189317/29497133-46533a86-85eb-11e7-945c-208118c4de32.jpg)

**Comment by chaoticnote** [comment]
Can confirm it's happening to me too.
Google Chrome Version 60.0.3112.101

**Comment by Cadrach** [comment]
Hi guys, I am on holidays so this will be solved in early September, sorry for the delay :/

**Comment by ChaPunch** [comment]
No problem, thanks for the response, at least we know it will be fixed, and thank you for this amazing site :D

**Comment by Cadrach** [comment]
Back from holidays, and I am unable to reproduce the issue on my side. Can you try clearing your cache and let me know if the problem is still there?

**Comment by mskovmose** [comment]
I have the exact same icons as OP and I have tried both on Chrome and Firefox with latest update. Has been going on for a while now and seems to be getting worse with every LoL update for some reason.

**Comment by Cadrach** [comment]
could you provide an export of your sets?

**Comment by mskovmose** [comment]
There is no problem with the sets, once I’m in game. It’s just the icons in your tool that are wrong. I have attached my ZIP file.

 

// Martin

 
[Lol_Item_Set.zip](https://github.com/Cadrach/lol_ise/files/1274887/Lol_Item_Set.zip)

**Comment by Cadrach** [comment]
Hi,

Sorry did not have time to check earlier. I used your file with no issue, and everything looks fine. Are you using the tool in a specific language other than english?

**Comment by mskovmose** [comment]
The issue was fixed a few days after I sent you the file, so I just assumed you found the bug.

 

// Martin

**Comment by Cadrach** [comment]
Must have been on Riot si de then :)
