### ISSUE TITLE
Jungle enchants aren't filtered according to their respective stats.

### ISSUE THREAD

**Issue by Aerhyce** [Cadrach/lol_ise#6]
### Browser (Chrome, Safari, Internet Explorer) and Version

Chrome, Firefox

### Steps to reproduce

Tick AD and/or CDR: Warrior enchantment does not show up despite giving AD and CDR.
Tick AP and/or Other MS: Runic Echoes does not show up.
Tick HP: Cinderhulk does not show up.

It may simply be an issue from Riot's end, as the enchantment do not show up either when filtering the stats they give in the official Item Set tool.

**Comment by Cadrach** [comment]
Added on 0.7
