### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by bernardmizzi** [Cadrach/lol_ise#61]
I'm currently a student doing my dissertation on runtime verification, is it possible to provide me a runnable version of this application so that I can use it as a use case?

**Comment by Cadrach** [comment]
I do not understand, you have a runable version on lol.item-set.com, or you can deploy one yourself since the sources are provided here.

Am I missing something?

**Comment by bernardmizzi** [comment]
Yes, I managed to set it up and run it locally. Thankyou
